# Generated by Django 4.2 on 2024-11-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_aboutme_techstack"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("grade", models.CharField(blank=True, max_length=50)),
                ("is_current", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Education",
                "ordering": ["order", "-start_date"],
            },
        ),
        migrations.AddField(
            model_name="aboutme",
            name="education",
            field=models.ManyToManyField(
                blank=True, related_name="about_me", to="api.education"
            ),
        ),
    ]
